config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :game_details

  resources :plays do
    get :make_move
    get :game_over
  end

  root to: 'home#index'
  

end

app/models/game_counter.rb
class GameCounter < ActiveRecord::Base
end

app/models/game_detail.rb
class GameDetail < ActiveRecord::Base
  has_many :plays
end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :play
end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :game_detail, :class_name => "GameDetail",
      :foreign_key => "game_id"
  belongs_to :user
  belongs_to :opponent, :class_name => "User", :foreign_key => "opponent_id"
  has_many :moves
  
  WINNING_LINES = [ [0,1,2],[0,3,6],[0,4,8],[1,4,7],[2,4,6],[2,5,8],[3,4,5],[6,7,8] ]

  def current_piece
    number_of_moves = self.moves.count
    if number_of_moves.even?
      "X"
    else
      "O"
    end
  end

  def current_player
    if self.moves.count.even?
      player = self.user
    else
      player = self.opponent
    end
    player
  end

  def display_board
    board = [nil,nil,nil,nil,nil,nil,nil,nil,nil]
    self.moves.each do |move|
      board[move.board_index] = move.symbol
    end
    board
  end

  def has_won?(symbol)
    board = display_board
    indices = []
    win = false
    board.each_with_index do |sq, index|
      indices << index if sq == symbol
    end
    WINNING_LINES.each do |wl|
      if indices & wl == wl
        win = true
        return true
      end
    end
    win
  end

  def board_full?
    display_board.all?
  end

  def game_over?
    board_full? || has_won?("X") || has_won?("O")
  end

  def computer_move
    board = display_board
    board.each_with_index do |sq, index|
      if sq == nil
        return index
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :plays
  has_many :plays, :class_name => "Play", :foreign_key => "opponent_id"
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_details_controller.rb
class GameDetailsController < ApplicationController
  def index
    @games = GameDetail.all
  end

  def show
    @game = GameDetail.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

  before_action :authenticate_user!, except: :index

  def index
  end

  def new
    # game = (params[:format])
    # @play = Play.new(game_id: game)
    @play = Play.new
    @games = GameDetail.all
    @users = User.all.reject {|user| user == current_user}
  end

  def create
    game_id = params[:play][:game_id].to_i
    opponent_id = params[:play][:opponent_id]
    if GameDetail.find(game_id).availability == "available"
      play = Play.create(user_id: current_user.id, game_id: game_id, opponent_id: opponent_id)
      redirect_to play_path(play)
    else
      message = "Sorry, that game is not available."
      redirect_to game_details_path( { message: message } )
    end
  end

  def show
    # raise
    @play = Play.find(params[:id])
    @board = @play.display_board
    @symbol = @play.current_piece
    if @symbol == "O" && @play.opponent.username == "Computer"
      redirect_to play_make_move_path(@play) 
    elsif @play.game_over?
      redirect_to play_game_over_path(@play)
    end
  end

  def game_over
    @play = Play.find(params[:play_id])
    @result = params[:result]
    @board = @play.display_board
    @symbol = params[:symbol]
  end

  def make_move
    play = Play.find(params[:play_id])
    symbol = play.current_piece
    if symbol == "O" && play.opponent.username.include?("Computer")
      board_index = play.computer_move
      play.moves.create(symbol: symbol, board_index: board_index)
    else
      play.moves.create(symbol: symbol, board_index: params[:board_index])
    end
    if play.has_won?(symbol)
      play.update(winner_id: current_user.id)
      redirect_to play_game_over_path(play, { play_id: play.id, result: "win", symbol: symbol })
    elsif play.board_full?
      play.update(winner_id: 0)
      redirect_to play_game_over_path(play, { play_id: play.id, result: "draw" })
    else
      redirect_to play_path(params[:play_id])
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/game_details/index.html.erb
<% if params[:message] %>
  <h4 class="error"><%= params[:message] %></h4>
<% end %>

<% @games.each do |game| %>
<div class="index-view">
  <%= image_tag game.image %>
  <br>
  <%= link_to game.name, game_detail_path(game) %>
  <br>
  <% if game.availability == "available" %>
    <p><%= link_to 'New game', new_play_path %></p>
  <% else %>
    <p>Coming soon...</p>
  <% end %>
</div>
<% end %>

app/views/game_details/show.html.erb
<div class="game-heading">
  <h2><%= @game.name %></h2>
  <p><%= link_to "Start new '#{@game.name}' game", new_play_path if @game.availability == "available" %></p>
  <p><%= "Coming soon!" if @game.availability != "available" %></p>
</div>
<%= image_tag @game.image %>
<h3>Description:</h3>
<p><%= @game.description %></p>

<% if @game.availability == "available" %>
  <%= link_to "Start new '#{@game.name}' game", new_play_path %>
<% end %>

app/views/games/_board.html.erb
<% p1_symbol = 'X' %>
<% p2_symbol = 'O' %>

<div class="board-container">
<% @board.each_with_index do |sq, index| %>
  <div class="sq">
    <% if sq.to_i == 1 %>
      <%= p1_symbol %>
    <% elsif sq.to_i == 2 %>
      <%= p2_symbol %>
    <% else %>
      <%= link_to 'here', game_make_move_path(@game, { move_index: index }) %>
    <% end %>
  </div>
<% end %>
</div>

app/views/games/new.html.erb
<%= render 'board' %>

app/views/home/index.html.erb
<p>A collection of classic board games to play online. Play against other users, and see your play history.</p>

<p>New games coming soon!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Online Gaming App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<nav>
  <div class="go-left">
    <%= link_to 'Home', root_path %>
    <%= link_to 'Games', game_details_path %>
    <% if current_user %>
      <%= link_to 'My Play History', plays_path({user_id: current_user.id}) %>
    <% end %>
  </div>
  <div class="go-right">
    <% if current_user %>
      Welcome, <%= link_to current_user.username, edit_user_registration_path %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Register', new_user_registration_path %>
    <% end %>
  </div>
</nav>

<header><h1>Online Gaming Portal</h1></header>

<%= yield %>

</body>
</html>

app/views/plays/_board.html.erb
<div class="board-container">
<% symbols = GameCounter.all %>
<% @board.each_with_index do |symbol, index| %>
    <div class="sq">
    <% if symbol == "X" || symbol == "O" %>
      <%= image_tag symbols.find_by_game_counter(symbol).game_counter_image %>
    <% else %>
      <%= link_to image_tag(symbols.find_by_game_counter(@symbol).game_counter_image), play_make_move_path(@play, { board_index: index }) unless @play.game_over? || @play.current_player != current_user %>
    <% end %>
    </div>
<% end %>
</div>

app/views/plays/_plays_table.html.erb
<table>
<thead>
  <th>Game</th>
  <th>User</th>
  <th>Opponent</th>
  <th>Started</th>
  <th>Result</th>
  <th>View Board</th>
</thead>


<% @plays.each do |play| %>
  <tr>
    <td><%= play.game_detail.name %></td>
    <td><%= play.user.username %></td>
    <td><%= play.opponent.username if play.opponent %></td>
    <td><%= time_ago_in_words(play.created_at) %> ago</td>
    <% if play.game_over? %>
      <% if play.winner_id == 0 %>
        <td class="result result-drawn">Draw</td>
      <% else %>
        <td class="result result-won">Won by <%= User.find(play.winner_id).username %></td>
        <% end %>
      <td><%= link_to 'view', play_path(play) %></td>
    <% else %>
      <td class="result result-ongoing">-in progress-</td>
      <% if current_user == play.user || current_user == play.opponent %>
        <td><%= link_to 'continue', play_path(play) %></td>
      <% else %>
        <td><%= link_to 'view', play_path(play) %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>

app/views/plays/_wins_table.html.erb
<table>
<thead>
  <th>Game</th>
  <th>User</th>
  <th>Opponent</th>
  <th>Started</th>
  <th>Result</th>
  <th>View Board</th>
</thead>


<% @plays.each do |play| %>
  <tr>
    <td><%= play.game_detail.name %></td>
    <td><%= play.user.username %></td>
    <td><%= play.opponent.username if play.opponent %></td>
    <td><%= time_ago_in_words(play.created_at) %> ago</td>
    <% if play.game_over? %>
      <% if play.winner_id == 0 %>
        <td class="result result-drawn">Draw</td>
      <% else %>
        <td class="result result-won">Won by <%= User.find(play.winner_id).username %></td>
        <% end %>
      <td><%= link_to 'view', play_path(play) %></td>
    <% else %>
      <td class="result result-ongoing">-in progress-</td>
      <% if current_user == play.user || current_user == play.opponent %>
        <td><%= link_to 'continue', play_path(play) %></td>
      <% else %>
        <td><%= link_to 'view', play_path(play) %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>

app/views/plays/game_over.html.erb
<h3>Game over</h3>
<% if @play.winner_id == 0 %>
  <p>It's a draw - everybody wins!</p>
<% else %>
  <p><%= User.find(@play.winner_id).username %> won!</p>
<% end %>

<div class="player go-left">
  <p><%= @play.user.username %></p>
  <p>( X )</p>
</div>
<div class="player go-right">
  <% if @play.opponent %>
    <p><%= @play.opponent.username %></p>
  <% else %>
    <p>Player 2</p>
  <% end %>
  <p>( O )</p>
</div>

<%= render 'board' %>

<%= link_to 'Play again?', new_play_path %>

app/views/plays/index.html.erb
<% if params[:user_id] %>
  <% current_user = params[:user_id] %>
  <% @plays = Play.where("user_id = #{current_user} OR opponent_id = #{current_user}") %>
  <h2>My Recent Games</h2>
  <% if @plays.empty? %>
    <p>Looks like you've not played any games yet. Click the link below to get started!</p>
  <% end %>
<% else %>
  <% @plays = Play.all %>
  <h2>Recently Played</h2>
<% end %>

<% @plays = @plays.order("created_at desc").limit(10) %>
<p><%= link_to 'Start New Game', new_play_path %></p>
<%= render 'plays_table' %>


<% counter = 0 %>
<% while counter < 10 do %>
<% counter += 1 %>
<% end %>

app/views/plays/new.html.erb
<%= form_for @play do |f| %>
  <%= f.label :game_id, 'Game:' %>
  <%= f.collection_select(:game_id, @games, :id, :name) %>
  <br>
  <%= f.label :opponent_id, 'Play against:' %>
  <%= f.collection_select(:opponent_id, @users, :id, :username) %>
  <br>
  <%= f.submit %>
<% end %>

app/views/plays/show.html.erb
<div class="player go-left">
  <p><%= @play.user.username %></p>
  <p>( X )</p>
</div>
<div class="player go-right">
  <% if @play.opponent %>
    <p><%= @play.opponent.username %></p>
  <% else %>
    <p>Player 2</p>
  <% end %>
  <p>( O )</p>
</div>


<%= render 'board' %>


<% if @play.current_player == current_user %>
  <p class="display-turn"><%= "#{@play.current_player.username}, it's your turn!" %></p>
<% else %>
  <p class="display-turn"><%= "Waiting for #{@play.current_player.username} to play..." %></p>
<% end %>